# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_win.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1218, 652)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMinimumSize(QtCore.QSize(1200, 598))
        self.tabWidget.setObjectName("tabWidget")
        self.kpaTab = QtWidgets.QWidget()
        self.kpaTab.setObjectName("kpaTab")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.kpaTab)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout.setObjectName("verticalLayout")
        self.powerGBox = QtWidgets.QGroupBox(self.kpaTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.powerGBox.sizePolicy().hasHeightForWidth())
        self.powerGBox.setSizePolicy(sizePolicy)
        self.powerGBox.setMinimumSize(QtCore.QSize(250, 70))
        self.powerGBox.setObjectName("powerGBox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.powerGBox)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.powOnPButt = QtWidgets.QPushButton(self.powerGBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.powOnPButt.sizePolicy().hasHeightForWidth())
        self.powOnPButt.setSizePolicy(sizePolicy)
        self.powOnPButt.setMinimumSize(QtCore.QSize(0, 30))
        self.powOnPButt.setObjectName("powOnPButt")
        self.gridLayout_3.addWidget(self.powOnPButt, 0, 0, 1, 1)
        self.powOffPButt = QtWidgets.QPushButton(self.powerGBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.powOffPButt.sizePolicy().hasHeightForWidth())
        self.powOffPButt.setSizePolicy(sizePolicy)
        self.powOffPButt.setMinimumSize(QtCore.QSize(0, 30))
        self.powOffPButt.setObjectName("powOffPButt")
        self.gridLayout_3.addWidget(self.powOffPButt, 0, 1, 1, 1)
        self.verticalLayout.addWidget(self.powerGBox)
        self.KUGBox = QtWidgets.QGroupBox(self.kpaTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.KUGBox.sizePolicy().hasHeightForWidth())
        self.KUGBox.setSizePolicy(sizePolicy)
        self.KUGBox.setMinimumSize(QtCore.QSize(250, 70))
        self.KUGBox.setObjectName("KUGBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.KUGBox)
        self.gridLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.durationSBox = QtWidgets.QSpinBox(self.KUGBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.durationSBox.sizePolicy().hasHeightForWidth())
        self.durationSBox.setSizePolicy(sizePolicy)
        self.durationSBox.setMinimumSize(QtCore.QSize(25, 25))
        self.durationSBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.durationSBox.setMinimum(15)
        self.durationSBox.setMaximum(500)
        self.durationSBox.setSingleStep(5)
        self.durationSBox.setProperty("value", 20)
        self.durationSBox.setObjectName("durationSBox")
        self.gridLayout_2.addWidget(self.durationSBox, 2, 4, 1, 1)
        self.durationLabel = QtWidgets.QLabel(self.KUGBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.durationLabel.sizePolicy().hasHeightForWidth())
        self.durationLabel.setSizePolicy(sizePolicy)
        self.durationLabel.setMinimumSize(QtCore.QSize(55, 25))
        self.durationLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.durationLabel.setObjectName("durationLabel")
        self.gridLayout_2.addWidget(self.durationLabel, 2, 2, 1, 1)
        self.onBEPButt = QtWidgets.QPushButton(self.KUGBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.onBEPButt.sizePolicy().hasHeightForWidth())
        self.onBEPButt.setSizePolicy(sizePolicy)
        self.onBEPButt.setMinimumSize(QtCore.QSize(30, 30))
        self.onBEPButt.setObjectName("onBEPButt")
        self.gridLayout_2.addWidget(self.onBEPButt, 2, 0, 1, 1)
        self.offBEPButt = QtWidgets.QPushButton(self.KUGBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.offBEPButt.sizePolicy().hasHeightForWidth())
        self.offBEPButt.setSizePolicy(sizePolicy)
        self.offBEPButt.setMinimumSize(QtCore.QSize(30, 30))
        self.offBEPButt.setObjectName("offBEPButt")
        self.gridLayout_2.addWidget(self.offBEPButt, 2, 1, 1, 1)
        self.verticalLayout.addWidget(self.KUGBox)
        self.testDEPPButt = QtWidgets.QGroupBox(self.kpaTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.testDEPPButt.sizePolicy().hasHeightForWidth())
        self.testDEPPButt.setSizePolicy(sizePolicy)
        self.testDEPPButt.setMinimumSize(QtCore.QSize(250, 70))
        self.testDEPPButt.setObjectName("testDEPPButt")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.testDEPPButt)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.depP30PButt = QtWidgets.QPushButton(self.testDEPPButt)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.depP30PButt.sizePolicy().hasHeightForWidth())
        self.depP30PButt.setSizePolicy(sizePolicy)
        self.depP30PButt.setMinimumSize(QtCore.QSize(0, 30))
        self.depP30PButt.setObjectName("depP30PButt")
        self.gridLayout_4.addWidget(self.depP30PButt, 0, 0, 1, 1)
        self.depM30PButt = QtWidgets.QPushButton(self.testDEPPButt)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.depM30PButt.sizePolicy().hasHeightForWidth())
        self.depM30PButt.setSizePolicy(sizePolicy)
        self.depM30PButt.setMinimumSize(QtCore.QSize(0, 30))
        self.depM30PButt.setObjectName("depM30PButt")
        self.gridLayout_4.addWidget(self.depM30PButt, 0, 1, 1, 1)
        self.dep0PButt = QtWidgets.QPushButton(self.testDEPPButt)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dep0PButt.sizePolicy().hasHeightForWidth())
        self.dep0PButt.setSizePolicy(sizePolicy)
        self.dep0PButt.setMinimumSize(QtCore.QSize(0, 30))
        self.dep0PButt.setObjectName("dep0PButt")
        self.gridLayout_4.addWidget(self.dep0PButt, 0, 2, 1, 1)
        self.verticalLayout.addWidget(self.testDEPPButt)
        self.testMPPPButt = QtWidgets.QGroupBox(self.kpaTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.testMPPPButt.sizePolicy().hasHeightForWidth())
        self.testMPPPButt.setSizePolicy(sizePolicy)
        self.testMPPPButt.setMinimumSize(QtCore.QSize(250, 100))
        self.testMPPPButt.setObjectName("testMPPPButt")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.testMPPPButt)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.pushButton_3 = QtWidgets.QPushButton(self.testMPPPButt)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_3.sizePolicy().hasHeightForWidth())
        self.pushButton_3.setSizePolicy(sizePolicy)
        self.pushButton_3.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout_5.addWidget(self.pushButton_3, 2, 2, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.testMPPPButt)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_4.sizePolicy().hasHeightForWidth())
        self.pushButton_4.setSizePolicy(sizePolicy)
        self.pushButton_4.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout_5.addWidget(self.pushButton_4, 2, 3, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.testMPPPButt)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_2.sizePolicy().hasHeightForWidth())
        self.pushButton_2.setSizePolicy(sizePolicy)
        self.pushButton_2.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_5.addWidget(self.pushButton_2, 0, 2, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.testMPPPButt)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_5.addWidget(self.pushButton, 0, 3, 1, 1)
        self.verticalLayout.addWidget(self.testMPPPButt)
        self.groupBox = QtWidgets.QGroupBox(self.kpaTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 100))
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_8.setVerticalSpacing(3)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.adcSinglePButt = QtWidgets.QPushButton(self.groupBox)
        self.adcSinglePButt.setMinimumSize(QtCore.QSize(0, 30))
        self.adcSinglePButt.setObjectName("adcSinglePButt")
        self.gridLayout_8.addWidget(self.adcSinglePButt, 0, 1, 1, 1)
        self.adcCycleCBox = QtWidgets.QCheckBox(self.groupBox)
        self.adcCycleCBox.setChecked(True)
        self.adcCycleCBox.setTristate(False)
        self.adcCycleCBox.setObjectName("adcCycleCBox")
        self.gridLayout_8.addWidget(self.adcCycleCBox, 0, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.adcPeriodLabel = QtWidgets.QLabel(self.groupBox)
        self.adcPeriodLabel.setMinimumSize(QtCore.QSize(100, 0))
        self.adcPeriodLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.adcPeriodLabel.setObjectName("adcPeriodLabel")
        self.horizontalLayout_4.addWidget(self.adcPeriodLabel)
        self.adcPeriodSBox = QtWidgets.QDoubleSpinBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.adcPeriodSBox.sizePolicy().hasHeightForWidth())
        self.adcPeriodSBox.setSizePolicy(sizePolicy)
        self.adcPeriodSBox.setMinimumSize(QtCore.QSize(25, 25))
        self.adcPeriodSBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.adcPeriodSBox.setDecimals(1)
        self.adcPeriodSBox.setMaximum(1000.0)
        self.adcPeriodSBox.setProperty("value", 2.0)
        self.adcPeriodSBox.setObjectName("adcPeriodSBox")
        self.horizontalLayout_4.addWidget(self.adcPeriodSBox)
        self.gridLayout_8.addLayout(self.horizontalLayout_4, 1, 0, 1, 2)
        self.verticalLayout.addWidget(self.groupBox)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.line = QtWidgets.QFrame(self.kpaTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line.sizePolicy().hasHeightForWidth())
        self.line.setSizePolicy(sizePolicy)
        self.line.setMinimumSize(QtCore.QSize(0, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.nanswKPALabel = QtWidgets.QLabel(self.kpaTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nanswKPALabel.sizePolicy().hasHeightForWidth())
        self.nanswKPALabel.setSizePolicy(sizePolicy)
        self.nanswKPALabel.setMinimumSize(QtCore.QSize(0, 30))
        self.nanswKPALabel.setAlignment(QtCore.Qt.AlignCenter)
        self.nanswKPALabel.setObjectName("nanswKPALabel")
        self.horizontalLayout_2.addWidget(self.nanswKPALabel)
        self.nanswKPASBox = QtWidgets.QSpinBox(self.kpaTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nanswKPASBox.sizePolicy().hasHeightForWidth())
        self.nanswKPASBox.setSizePolicy(sizePolicy)
        self.nanswKPASBox.setMinimumSize(QtCore.QSize(50, 30))
        self.nanswKPASBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.nanswKPASBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.nanswKPASBox.setObjectName("nanswKPASBox")
        self.horizontalLayout_2.addWidget(self.nanswKPASBox)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.DataTable = QtWidgets.QTableWidget(self.kpaTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DataTable.sizePolicy().hasHeightForWidth())
        self.DataTable.setSizePolicy(sizePolicy)
        self.DataTable.setMinimumSize(QtCore.QSize(250, 0))
        self.DataTable.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.DataTable.setRowCount(16)
        self.DataTable.setObjectName("DataTable")
        self.DataTable.setColumnCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.DataTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.DataTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.DataTable.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.DataTable.setItem(1, 1, item)
        self.DataTable.horizontalHeader().setCascadingSectionResizes(False)
        self.DataTable.horizontalHeader().setDefaultSectionSize(130)
        self.DataTable.horizontalHeader().setMinimumSectionSize(100)
        self.DataTable.horizontalHeader().setStretchLastSection(True)
        self.DataTable.verticalHeader().setDefaultSectionSize(25)
        self.verticalLayout_4.addWidget(self.DataTable)
        self.ClearLogPButt = QtWidgets.QPushButton(self.kpaTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ClearLogPButt.sizePolicy().hasHeightForWidth())
        self.ClearLogPButt.setSizePolicy(sizePolicy)
        self.ClearLogPButt.setMinimumSize(QtCore.QSize(140, 30))
        self.ClearLogPButt.setObjectName("ClearLogPButt")
        self.verticalLayout_4.addWidget(self.ClearLogPButt)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.LogTEdit = QtWidgets.QTextEdit(self.kpaTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LogTEdit.sizePolicy().hasHeightForWidth())
        self.LogTEdit.setSizePolicy(sizePolicy)
        self.LogTEdit.setMinimumSize(QtCore.QSize(630, 0))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(8)
        self.LogTEdit.setFont(font)
        self.LogTEdit.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.LogTEdit.setReadOnly(True)
        self.LogTEdit.setObjectName("LogTEdit")
        self.gridLayout.addWidget(self.LogTEdit, 1, 0, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout)
        self.horizontalLayout.setStretch(2, 1)
        self.tabWidget.addTab(self.kpaTab, "")
        self.mkoTab = QtWidgets.QWidget()
        self.mkoTab.setObjectName("mkoTab")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.mkoTab)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.scrollArea = QtWidgets.QScrollArea(self.mkoTab)
        self.scrollArea.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setMinimumSize(QtCore.QSize(750, 100))
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 748, 550))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayout_3.addWidget(self.scrollArea)
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.LoadCfgPButt = QtWidgets.QPushButton(self.mkoTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LoadCfgPButt.sizePolicy().hasHeightForWidth())
        self.LoadCfgPButt.setSizePolicy(sizePolicy)
        self.LoadCfgPButt.setMinimumSize(QtCore.QSize(130, 0))
        self.LoadCfgPButt.setObjectName("LoadCfgPButt")
        self.gridLayout_6.addWidget(self.LoadCfgPButt, 7, 0, 1, 2)
        self.DltUnitNumSBox = QtWidgets.QSpinBox(self.mkoTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DltUnitNumSBox.sizePolicy().hasHeightForWidth())
        self.DltUnitNumSBox.setSizePolicy(sizePolicy)
        self.DltUnitNumSBox.setMinimumSize(QtCore.QSize(0, 25))
        self.DltUnitNumSBox.setObjectName("DltUnitNumSBox")
        self.gridLayout_6.addWidget(self.DltUnitNumSBox, 1, 1, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.mkoTab)
        self.line_2.setMinimumSize(QtCore.QSize(130, 0))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_6.addWidget(self.line_2, 3, 0, 1, 2)
        self.DltUnitPButt = QtWidgets.QPushButton(self.mkoTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DltUnitPButt.sizePolicy().hasHeightForWidth())
        self.DltUnitPButt.setSizePolicy(sizePolicy)
        self.DltUnitPButt.setMinimumSize(QtCore.QSize(60, 25))
        self.DltUnitPButt.setObjectName("DltUnitPButt")
        self.gridLayout_6.addWidget(self.DltUnitPButt, 1, 0, 1, 1)
        self.DltAllUnitsPButt = QtWidgets.QPushButton(self.mkoTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DltAllUnitsPButt.sizePolicy().hasHeightForWidth())
        self.DltAllUnitsPButt.setSizePolicy(sizePolicy)
        self.DltAllUnitsPButt.setMinimumSize(QtCore.QSize(130, 0))
        self.DltAllUnitsPButt.setObjectName("DltAllUnitsPButt")
        self.gridLayout_6.addWidget(self.DltAllUnitsPButt, 2, 0, 1, 2)
        self.SaveCfgPButt = QtWidgets.QPushButton(self.mkoTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SaveCfgPButt.sizePolicy().hasHeightForWidth())
        self.SaveCfgPButt.setSizePolicy(sizePolicy)
        self.SaveCfgPButt.setMinimumSize(QtCore.QSize(130, 0))
        self.SaveCfgPButt.setObjectName("SaveCfgPButt")
        self.gridLayout_6.addWidget(self.SaveCfgPButt, 8, 0, 1, 2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem1, 9, 0, 1, 2)
        self.AddUnitPButt = QtWidgets.QPushButton(self.mkoTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.AddUnitPButt.sizePolicy().hasHeightForWidth())
        self.AddUnitPButt.setSizePolicy(sizePolicy)
        self.AddUnitPButt.setMinimumSize(QtCore.QSize(130, 0))
        self.AddUnitPButt.setObjectName("AddUnitPButt")
        self.gridLayout_6.addWidget(self.AddUnitPButt, 0, 0, 1, 2)
        self.mkoPollingPBar = QtWidgets.QProgressBar(self.mkoTab)
        self.mkoPollingPBar.setProperty("value", 0)
        self.mkoPollingPBar.setObjectName("mkoPollingPBar")
        self.gridLayout_6.addWidget(self.mkoPollingPBar, 5, 0, 1, 2)
        self.line_5 = QtWidgets.QFrame(self.mkoTab)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.gridLayout_6.addWidget(self.line_5, 6, 0, 1, 2)
        self.mkoPollingPButt = QtWidgets.QPushButton(self.mkoTab)
        self.mkoPollingPButt.setObjectName("mkoPollingPButt")
        self.gridLayout_6.addWidget(self.mkoPollingPButt, 4, 0, 1, 2)
        self.horizontalLayout_3.addLayout(self.gridLayout_6)
        self.DataTable_2 = QtWidgets.QTableWidget(self.mkoTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DataTable_2.sizePolicy().hasHeightForWidth())
        self.DataTable_2.setSizePolicy(sizePolicy)
        self.DataTable_2.setMinimumSize(QtCore.QSize(250, 0))
        self.DataTable_2.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.DataTable_2.setRowCount(20)
        self.DataTable_2.setObjectName("DataTable_2")
        self.DataTable_2.setColumnCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.DataTable_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.DataTable_2.setHorizontalHeaderItem(1, item)
        self.DataTable_2.horizontalHeader().setCascadingSectionResizes(False)
        self.DataTable_2.horizontalHeader().setDefaultSectionSize(150)
        self.DataTable_2.horizontalHeader().setMinimumSectionSize(50)
        self.DataTable_2.horizontalHeader().setStretchLastSection(True)
        self.DataTable_2.verticalHeader().setDefaultSectionSize(25)
        self.horizontalLayout_3.addWidget(self.DataTable_2)
        self.gridLayout_7.addLayout(self.horizontalLayout_3, 0, 0, 1, 1)
        self.tabWidget.addTab(self.mkoTab, "")
        self.verticalLayout_2.addWidget(self.tabWidget)
        self.statusTEdit = QtWidgets.QTextEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.statusTEdit.sizePolicy().hasHeightForWidth())
        self.statusTEdit.setSizePolicy(sizePolicy)
        self.statusTEdit.setMinimumSize(QtCore.QSize(0, 30))
        self.statusTEdit.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.statusTEdit.setFont(font)
        self.statusTEdit.setAutoFillBackground(False)
        self.statusTEdit.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.statusTEdit.setFrameShadow(QtWidgets.QFrame.Raised)
        self.statusTEdit.setLineWidth(0)
        self.statusTEdit.setObjectName("statusTEdit")
        self.verticalLayout_2.addWidget(self.statusTEdit)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.powerGBox.setTitle(_translate("MainWindow", "Питание"))
        self.powOnPButt.setText(_translate("MainWindow", "Включить"))
        self.powOffPButt.setText(_translate("MainWindow", "Выключить"))
        self.KUGBox.setTitle(_translate("MainWindow", "Команды управления"))
        self.durationLabel.setText(_translate("MainWindow", "Tpulse, мс"))
        self.onBEPButt.setText(_translate("MainWindow", "ВКЛ БЭ"))
        self.offBEPButt.setText(_translate("MainWindow", "ВЫКЛ БЭ"))
        self.testDEPPButt.setTitle(_translate("MainWindow", "Тестовый сигнал для ДЭП-ов"))
        self.depP30PButt.setText(_translate("MainWindow", "+ U"))
        self.depM30PButt.setText(_translate("MainWindow", "- U"))
        self.dep0PButt.setText(_translate("MainWindow", "0 В"))
        self.testMPPPButt.setTitle(_translate("MainWindow", "Тестовый сигнал МПП"))
        self.pushButton_3.setText(_translate("MainWindow", "Канал 2"))
        self.pushButton_4.setText(_translate("MainWindow", "Канал 4"))
        self.pushButton_2.setText(_translate("MainWindow", "Канал 1"))
        self.pushButton.setText(_translate("MainWindow", "Канал 3"))
        self.groupBox.setTitle(_translate("MainWindow", "АЦП КПА"))
        self.adcSinglePButt.setText(_translate("MainWindow", "Разовый запрос"))
        self.adcCycleCBox.setText(_translate("MainWindow", "Циклический опрос"))
        self.adcPeriodLabel.setText(_translate("MainWindow", "Интервал цикл. опроса, с:"))
        self.nanswKPALabel.setText(_translate("MainWindow", "Количество неответов КПА, шт"))
        item = self.DataTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Имя"))
        item = self.DataTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Значение"))
        __sortingEnabled = self.DataTable.isSortingEnabled()
        self.DataTable.setSortingEnabled(False)
        self.DataTable.setSortingEnabled(__sortingEnabled)
        self.ClearLogPButt.setText(_translate("MainWindow", "Очистить лог"))
        self.LogTEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Courier New\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'PT Serif\'; font-size:8.25pt;\"><br /></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.kpaTab), _translate("MainWindow", "КПА"))
        self.LoadCfgPButt.setText(_translate("MainWindow", "Загрузить"))
        self.DltUnitPButt.setText(_translate("MainWindow", "Удалить"))
        self.DltAllUnitsPButt.setText(_translate("MainWindow", "Удалить все"))
        self.SaveCfgPButt.setText(_translate("MainWindow", "Сохранить"))
        self.AddUnitPButt.setText(_translate("MainWindow", "Добавить"))
        self.mkoPollingPButt.setText(_translate("MainWindow", "Опрос всего по очереди"))
        item = self.DataTable_2.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Имя"))
        item = self.DataTable_2.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Значение"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.mkoTab), _translate("MainWindow", "МКО"))

