# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_win.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_main_win(object):
    def setupUi(self, main_win):
        main_win.setObjectName("main_win")
        main_win.resize(1336, 757)
        self.centralwidget = QtWidgets.QWidget(main_win)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.statusTEdit = QtWidgets.QTextEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.statusTEdit.sizePolicy().hasHeightForWidth())
        self.statusTEdit.setSizePolicy(sizePolicy)
        self.statusTEdit.setMinimumSize(QtCore.QSize(100, 30))
        self.statusTEdit.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.statusTEdit.setFont(font)
        self.statusTEdit.setAutoFillBackground(False)
        self.statusTEdit.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.statusTEdit.setFrameShadow(QtWidgets.QFrame.Raised)
        self.statusTEdit.setLineWidth(0)
        self.statusTEdit.setObjectName("statusTEdit")
        self.horizontalLayout_5.addWidget(self.statusTEdit)
        self.logsUpdatePButt = QtWidgets.QPushButton(self.centralwidget)
        self.logsUpdatePButt.setMinimumSize(QtCore.QSize(0, 30))
        self.logsUpdatePButt.setObjectName("logsUpdatePButt")
        self.horizontalLayout_5.addWidget(self.logsUpdatePButt)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.connectPButt = QtWidgets.QPushButton(self.centralwidget)
        self.connectPButt.setMinimumSize(QtCore.QSize(0, 30))
        self.connectPButt.setObjectName("connectPButt")
        self.horizontalLayout_5.addWidget(self.connectPButt)
        self.disconnectPButt = QtWidgets.QPushButton(self.centralwidget)
        self.disconnectPButt.setMinimumSize(QtCore.QSize(0, 30))
        self.disconnectPButt.setObjectName("disconnectPButt")
        self.horizontalLayout_5.addWidget(self.disconnectPButt)
        self.gridLayout_14.addLayout(self.horizontalLayout_5, 1, 0, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMinimumSize(QtCore.QSize(1310, 600))
        self.tabWidget.setObjectName("tabWidget")
        self.SKETab = QtWidgets.QWidget()
        self.SKETab.setObjectName("SKETab")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.SKETab)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.SKE_powerGBox = QtWidgets.QGroupBox(self.SKETab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SKE_powerGBox.sizePolicy().hasHeightForWidth())
        self.SKE_powerGBox.setSizePolicy(sizePolicy)
        self.SKE_powerGBox.setMinimumSize(QtCore.QSize(230, 70))
        self.SKE_powerGBox.setObjectName("SKE_powerGBox")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.SKE_powerGBox)
        self.gridLayout_10.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.SKE_powOnPButt = QtWidgets.QPushButton(self.SKE_powerGBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SKE_powOnPButt.sizePolicy().hasHeightForWidth())
        self.SKE_powOnPButt.setSizePolicy(sizePolicy)
        self.SKE_powOnPButt.setMinimumSize(QtCore.QSize(0, 30))
        self.SKE_powOnPButt.setObjectName("SKE_powOnPButt")
        self.gridLayout_10.addWidget(self.SKE_powOnPButt, 0, 0, 1, 1)
        self.SKE_powOffPButt = QtWidgets.QPushButton(self.SKE_powerGBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SKE_powOffPButt.sizePolicy().hasHeightForWidth())
        self.SKE_powOffPButt.setSizePolicy(sizePolicy)
        self.SKE_powOffPButt.setMinimumSize(QtCore.QSize(0, 30))
        self.SKE_powOffPButt.setObjectName("SKE_powOffPButt")
        self.gridLayout_10.addWidget(self.SKE_powOffPButt, 0, 1, 1, 1)
        self.gridLayout_10.setColumnStretch(0, 1)
        self.gridLayout_10.setColumnStretch(1, 1)
        self.verticalLayout_3.addWidget(self.SKE_powerGBox)
        self.SKE_KUGBox = QtWidgets.QGroupBox(self.SKETab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SKE_KUGBox.sizePolicy().hasHeightForWidth())
        self.SKE_KUGBox.setSizePolicy(sizePolicy)
        self.SKE_KUGBox.setMinimumSize(QtCore.QSize(230, 70))
        self.SKE_KUGBox.setObjectName("SKE_KUGBox")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.SKE_KUGBox)
        self.gridLayout_11.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.SKE_durationSBox = QtWidgets.QSpinBox(self.SKE_KUGBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SKE_durationSBox.sizePolicy().hasHeightForWidth())
        self.SKE_durationSBox.setSizePolicy(sizePolicy)
        self.SKE_durationSBox.setMinimumSize(QtCore.QSize(25, 30))
        self.SKE_durationSBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.SKE_durationSBox.setMinimum(15)
        self.SKE_durationSBox.setMaximum(500)
        self.SKE_durationSBox.setSingleStep(5)
        self.SKE_durationSBox.setProperty("value", 20)
        self.SKE_durationSBox.setObjectName("SKE_durationSBox")
        self.gridLayout_11.addWidget(self.SKE_durationSBox, 2, 4, 1, 1)
        self.SKE_durationLabel = QtWidgets.QLabel(self.SKE_KUGBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SKE_durationLabel.sizePolicy().hasHeightForWidth())
        self.SKE_durationLabel.setSizePolicy(sizePolicy)
        self.SKE_durationLabel.setMinimumSize(QtCore.QSize(50, 30))
        self.SKE_durationLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.SKE_durationLabel.setObjectName("SKE_durationLabel")
        self.gridLayout_11.addWidget(self.SKE_durationLabel, 2, 2, 1, 1)
        self.SKE_onBEPButt = QtWidgets.QPushButton(self.SKE_KUGBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SKE_onBEPButt.sizePolicy().hasHeightForWidth())
        self.SKE_onBEPButt.setSizePolicy(sizePolicy)
        self.SKE_onBEPButt.setMinimumSize(QtCore.QSize(50, 30))
        self.SKE_onBEPButt.setObjectName("SKE_onBEPButt")
        self.gridLayout_11.addWidget(self.SKE_onBEPButt, 2, 0, 1, 1)
        self.SKE_offBEPButt = QtWidgets.QPushButton(self.SKE_KUGBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SKE_offBEPButt.sizePolicy().hasHeightForWidth())
        self.SKE_offBEPButt.setSizePolicy(sizePolicy)
        self.SKE_offBEPButt.setMinimumSize(QtCore.QSize(50, 30))
        self.SKE_offBEPButt.setObjectName("SKE_offBEPButt")
        self.gridLayout_11.addWidget(self.SKE_offBEPButt, 2, 1, 1, 1)
        self.verticalLayout_3.addWidget(self.SKE_KUGBox)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.SKE_powDataGBox = QtWidgets.QGroupBox(self.SKETab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SKE_powDataGBox.sizePolicy().hasHeightForWidth())
        self.SKE_powDataGBox.setSizePolicy(sizePolicy)
        self.SKE_powDataGBox.setMinimumSize(QtCore.QSize(110, 120))
        self.SKE_powDataGBox.setObjectName("SKE_powDataGBox")
        self.gridLayout_17 = QtWidgets.QGridLayout(self.SKE_powDataGBox)
        self.gridLayout_17.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.gridLayout_17.setVerticalSpacing(2)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.SKE_powULabel = QtWidgets.QLabel(self.SKE_powDataGBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SKE_powULabel.sizePolicy().hasHeightForWidth())
        self.SKE_powULabel.setSizePolicy(sizePolicy)
        self.SKE_powULabel.setObjectName("SKE_powULabel")
        self.gridLayout_17.addWidget(self.SKE_powULabel, 0, 0, 1, 1)
        self.SKE_powLabel = QtWidgets.QLabel(self.SKE_powDataGBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SKE_powLabel.sizePolicy().hasHeightForWidth())
        self.SKE_powLabel.setSizePolicy(sizePolicy)
        self.SKE_powLabel.setObjectName("SKE_powLabel")
        self.gridLayout_17.addWidget(self.SKE_powLabel, 4, 0, 1, 1)
        self.SKE_powILabel = QtWidgets.QLabel(self.SKE_powDataGBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SKE_powILabel.sizePolicy().hasHeightForWidth())
        self.SKE_powILabel.setSizePolicy(sizePolicy)
        self.SKE_powILabel.setObjectName("SKE_powILabel")
        self.gridLayout_17.addWidget(self.SKE_powILabel, 2, 0, 1, 1)
        self.SKE_powWDSBox = QtWidgets.QDoubleSpinBox(self.SKE_powDataGBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SKE_powWDSBox.sizePolicy().hasHeightForWidth())
        self.SKE_powWDSBox.setSizePolicy(sizePolicy)
        self.SKE_powWDSBox.setMinimumSize(QtCore.QSize(30, 20))
        self.SKE_powWDSBox.setAlignment(QtCore.Qt.AlignCenter)
        self.SKE_powWDSBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.SKE_powWDSBox.setMaximum(10000.0)
        self.SKE_powWDSBox.setObjectName("SKE_powWDSBox")
        self.gridLayout_17.addWidget(self.SKE_powWDSBox, 4, 1, 1, 1)
        self.line_12 = QtWidgets.QFrame(self.SKE_powDataGBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_12.sizePolicy().hasHeightForWidth())
        self.line_12.setSizePolicy(sizePolicy)
        self.line_12.setMinimumSize(QtCore.QSize(0, 10))
        self.line_12.setLineWidth(2)
        self.line_12.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.gridLayout_17.addWidget(self.line_12, 3, 0, 1, 1)
        self.line_13 = QtWidgets.QFrame(self.SKE_powDataGBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_13.sizePolicy().hasHeightForWidth())
        self.line_13.setSizePolicy(sizePolicy)
        self.line_13.setMinimumSize(QtCore.QSize(0, 10))
        self.line_13.setLineWidth(2)
        self.line_13.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_13.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_13.setObjectName("line_13")
        self.gridLayout_17.addWidget(self.line_13, 1, 0, 1, 1)
        self.SKE_powIDSBox = QtWidgets.QDoubleSpinBox(self.SKE_powDataGBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SKE_powIDSBox.sizePolicy().hasHeightForWidth())
        self.SKE_powIDSBox.setSizePolicy(sizePolicy)
        self.SKE_powIDSBox.setMinimumSize(QtCore.QSize(30, 20))
        self.SKE_powIDSBox.setAlignment(QtCore.Qt.AlignCenter)
        self.SKE_powIDSBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.SKE_powIDSBox.setMaximum(10000.0)
        self.SKE_powIDSBox.setObjectName("SKE_powIDSBox")
        self.gridLayout_17.addWidget(self.SKE_powIDSBox, 2, 1, 1, 1)
        self.SKE_powUDSBox = QtWidgets.QDoubleSpinBox(self.SKE_powDataGBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SKE_powUDSBox.sizePolicy().hasHeightForWidth())
        self.SKE_powUDSBox.setSizePolicy(sizePolicy)
        self.SKE_powUDSBox.setMinimumSize(QtCore.QSize(30, 20))
        self.SKE_powUDSBox.setAlignment(QtCore.Qt.AlignCenter)
        self.SKE_powUDSBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.SKE_powUDSBox.setMaximum(10000.0)
        self.SKE_powUDSBox.setObjectName("SKE_powUDSBox")
        self.gridLayout_17.addWidget(self.SKE_powUDSBox, 0, 1, 1, 1)
        self.horizontalLayout_8.addWidget(self.SKE_powDataGBox)
        self.groupBox_7 = QtWidgets.QGroupBox(self.SKETab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_7.sizePolicy().hasHeightForWidth())
        self.groupBox_7.setSizePolicy(sizePolicy)
        self.groupBox_7.setMinimumSize(QtCore.QSize(110, 120))
        self.groupBox_7.setObjectName("groupBox_7")
        self.gridLayout_18 = QtWidgets.QGridLayout(self.groupBox_7)
        self.gridLayout_18.setVerticalSpacing(2)
        self.gridLayout_18.setObjectName("gridLayout_18")
        self.SKE_stmNormCM_Label = QtWidgets.QLabel(self.groupBox_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SKE_stmNormCM_Label.sizePolicy().hasHeightForWidth())
        self.SKE_stmNormCM_Label.setSizePolicy(sizePolicy)
        self.SKE_stmNormCM_Label.setObjectName("SKE_stmNormCM_Label")
        self.gridLayout_18.addWidget(self.SKE_stmNormCM_Label, 3, 0, 1, 1)
        self.SKE_stmAMKO_Label = QtWidgets.QLabel(self.groupBox_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SKE_stmAMKO_Label.sizePolicy().hasHeightForWidth())
        self.SKE_stmAMKO_Label.setSizePolicy(sizePolicy)
        self.SKE_stmAMKO_Label.setObjectName("SKE_stmAMKO_Label")
        self.gridLayout_18.addWidget(self.SKE_stmAMKO_Label, 5, 0, 1, 1)
        self.SKE_stm_KPBE_DSBox = QtWidgets.QDoubleSpinBox(self.groupBox_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SKE_stm_KPBE_DSBox.sizePolicy().hasHeightForWidth())
        self.SKE_stm_KPBE_DSBox.setSizePolicy(sizePolicy)
        self.SKE_stm_KPBE_DSBox.setMinimumSize(QtCore.QSize(30, 20))
        self.SKE_stm_KPBE_DSBox.setAlignment(QtCore.Qt.AlignCenter)
        self.SKE_stm_KPBE_DSBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.SKE_stm_KPBE_DSBox.setMaximum(10000.0)
        self.SKE_stm_KPBE_DSBox.setObjectName("SKE_stm_KPBE_DSBox")
        self.gridLayout_18.addWidget(self.SKE_stm_KPBE_DSBox, 0, 1, 1, 1)
        self.SKE_stmKPBE_Label = QtWidgets.QLabel(self.groupBox_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SKE_stmKPBE_Label.sizePolicy().hasHeightForWidth())
        self.SKE_stmKPBE_Label.setSizePolicy(sizePolicy)
        self.SKE_stmKPBE_Label.setObjectName("SKE_stmKPBE_Label")
        self.gridLayout_18.addWidget(self.SKE_stmKPBE_Label, 0, 0, 1, 1)
        self.SKE_stm_AMKO_DSBox = QtWidgets.QDoubleSpinBox(self.groupBox_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SKE_stm_AMKO_DSBox.sizePolicy().hasHeightForWidth())
        self.SKE_stm_AMKO_DSBox.setSizePolicy(sizePolicy)
        self.SKE_stm_AMKO_DSBox.setMinimumSize(QtCore.QSize(30, 20))
        self.SKE_stm_AMKO_DSBox.setAlignment(QtCore.Qt.AlignCenter)
        self.SKE_stm_AMKO_DSBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.SKE_stm_AMKO_DSBox.setMaximum(10000.0)
        self.SKE_stm_AMKO_DSBox.setObjectName("SKE_stm_AMKO_DSBox")
        self.gridLayout_18.addWidget(self.SKE_stm_AMKO_DSBox, 5, 1, 1, 1)
        self.line_15 = QtWidgets.QFrame(self.groupBox_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_15.sizePolicy().hasHeightForWidth())
        self.line_15.setSizePolicy(sizePolicy)
        self.line_15.setMinimumSize(QtCore.QSize(0, 10))
        self.line_15.setLineWidth(2)
        self.line_15.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_15.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_15.setObjectName("line_15")
        self.gridLayout_18.addWidget(self.line_15, 4, 0, 1, 1)
        self.line_14 = QtWidgets.QFrame(self.groupBox_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_14.sizePolicy().hasHeightForWidth())
        self.line_14.setSizePolicy(sizePolicy)
        self.line_14.setMinimumSize(QtCore.QSize(0, 10))
        self.line_14.setLineWidth(2)
        self.line_14.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_14.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_14.setObjectName("line_14")
        self.gridLayout_18.addWidget(self.line_14, 2, 0, 1, 1)
        self.SKE_stm_NormCM_DSBox = QtWidgets.QDoubleSpinBox(self.groupBox_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SKE_stm_NormCM_DSBox.sizePolicy().hasHeightForWidth())
        self.SKE_stm_NormCM_DSBox.setSizePolicy(sizePolicy)
        self.SKE_stm_NormCM_DSBox.setMinimumSize(QtCore.QSize(30, 20))
        self.SKE_stm_NormCM_DSBox.setAlignment(QtCore.Qt.AlignCenter)
        self.SKE_stm_NormCM_DSBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.SKE_stm_NormCM_DSBox.setMaximum(10000.0)
        self.SKE_stm_NormCM_DSBox.setObjectName("SKE_stm_NormCM_DSBox")
        self.gridLayout_18.addWidget(self.SKE_stm_NormCM_DSBox, 3, 1, 1, 1)
        self.horizontalLayout_8.addWidget(self.groupBox_7)
        self.verticalLayout_3.addLayout(self.horizontalLayout_8)
        self.SKE_measIntervalGBox = QtWidgets.QGroupBox(self.SKETab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SKE_measIntervalGBox.sizePolicy().hasHeightForWidth())
        self.SKE_measIntervalGBox.setSizePolicy(sizePolicy)
        self.SKE_measIntervalGBox.setMinimumSize(QtCore.QSize(230, 100))
        self.SKE_measIntervalGBox.setObjectName("SKE_measIntervalGBox")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.SKE_measIntervalGBox)
        self.gridLayout_13.setSpacing(5)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.SKE_mInterval60sRButt = QtWidgets.QRadioButton(self.SKE_measIntervalGBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SKE_mInterval60sRButt.sizePolicy().hasHeightForWidth())
        self.SKE_mInterval60sRButt.setSizePolicy(sizePolicy)
        self.SKE_mInterval60sRButt.setMinimumSize(QtCore.QSize(100, 30))
        self.SKE_mInterval60sRButt.setChecked(False)
        self.SKE_mInterval60sRButt.setObjectName("SKE_mInterval60sRButt")
        self.gridLayout_13.addWidget(self.SKE_mInterval60sRButt, 1, 0, 1, 1)
        self.SKE_mInterval240sRButt = QtWidgets.QRadioButton(self.SKE_measIntervalGBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SKE_mInterval240sRButt.sizePolicy().hasHeightForWidth())
        self.SKE_mInterval240sRButt.setSizePolicy(sizePolicy)
        self.SKE_mInterval240sRButt.setMinimumSize(QtCore.QSize(100, 30))
        self.SKE_mInterval240sRButt.setObjectName("SKE_mInterval240sRButt")
        self.gridLayout_13.addWidget(self.SKE_mInterval240sRButt, 3, 0, 1, 1)
        self.SKE_mInterval120sRButt = QtWidgets.QRadioButton(self.SKE_measIntervalGBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SKE_mInterval120sRButt.sizePolicy().hasHeightForWidth())
        self.SKE_mInterval120sRButt.setSizePolicy(sizePolicy)
        self.SKE_mInterval120sRButt.setMinimumSize(QtCore.QSize(100, 30))
        self.SKE_mInterval120sRButt.setObjectName("SKE_mInterval120sRButt")
        self.gridLayout_13.addWidget(self.SKE_mInterval120sRButt, 2, 0, 1, 1)
        self.SKE_mInterval1sPButton = QtWidgets.QPushButton(self.SKE_measIntervalGBox)
        self.SKE_mInterval1sPButton.setMinimumSize(QtCore.QSize(0, 30))
        self.SKE_mInterval1sPButton.setCheckable(True)
        self.SKE_mInterval1sPButton.setObjectName("SKE_mInterval1sPButton")
        self.gridLayout_13.addWidget(self.SKE_mInterval1sPButton, 1, 1, 1, 1)
        self.SKE_dbgMIntPbutton = QtWidgets.QPushButton(self.SKE_measIntervalGBox)
        self.SKE_dbgMIntPbutton.setMinimumSize(QtCore.QSize(0, 30))
        self.SKE_dbgMIntPbutton.setCheckable(True)
        self.SKE_dbgMIntPbutton.setObjectName("SKE_dbgMIntPbutton")
        self.gridLayout_13.addWidget(self.SKE_dbgMIntPbutton, 3, 1, 1, 1)
        self.verticalLayout_3.addWidget(self.SKE_measIntervalGBox)
        self.SKE_testDEPPButt = QtWidgets.QGroupBox(self.SKETab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SKE_testDEPPButt.sizePolicy().hasHeightForWidth())
        self.SKE_testDEPPButt.setSizePolicy(sizePolicy)
        self.SKE_testDEPPButt.setMinimumSize(QtCore.QSize(230, 170))
        self.SKE_testDEPPButt.setObjectName("SKE_testDEPPButt")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.SKE_testDEPPButt)
        self.gridLayout_12.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.gridLayout_12.setContentsMargins(6, 6, 6, 6)
        self.gridLayout_12.setSpacing(5)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.SKE_dnp_drp_PButt = QtWidgets.QPushButton(self.SKE_testDEPPButt)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SKE_dnp_drp_PButt.sizePolicy().hasHeightForWidth())
        self.SKE_dnp_drp_PButt.setSizePolicy(sizePolicy)
        self.SKE_dnp_drp_PButt.setMinimumSize(QtCore.QSize(0, 30))
        self.SKE_dnp_drp_PButt.setObjectName("SKE_dnp_drp_PButt")
        self.gridLayout_12.addWidget(self.SKE_dnp_drp_PButt, 2, 2, 1, 1)
        self.SKE_dep0PButt = QtWidgets.QPushButton(self.SKE_testDEPPButt)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SKE_dep0PButt.sizePolicy().hasHeightForWidth())
        self.SKE_dep0PButt.setSizePolicy(sizePolicy)
        self.SKE_dep0PButt.setMinimumSize(QtCore.QSize(0, 30))
        self.SKE_dep0PButt.setObjectName("SKE_dep0PButt")
        self.gridLayout_12.addWidget(self.SKE_dep0PButt, 0, 3, 1, 1)
        self.SKE_depP30PButt = QtWidgets.QPushButton(self.SKE_testDEPPButt)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SKE_depP30PButt.sizePolicy().hasHeightForWidth())
        self.SKE_depP30PButt.setSizePolicy(sizePolicy)
        self.SKE_depP30PButt.setMinimumSize(QtCore.QSize(0, 30))
        self.SKE_depP30PButt.setObjectName("SKE_depP30PButt")
        self.gridLayout_12.addWidget(self.SKE_depP30PButt, 0, 1, 1, 1)
        self.SKE_mpp12PButt = QtWidgets.QPushButton(self.SKE_testDEPPButt)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SKE_mpp12PButt.sizePolicy().hasHeightForWidth())
        self.SKE_mpp12PButt.setSizePolicy(sizePolicy)
        self.SKE_mpp12PButt.setMinimumSize(QtCore.QSize(0, 30))
        self.SKE_mpp12PButt.setObjectName("SKE_mpp12PButt")
        self.gridLayout_12.addWidget(self.SKE_mpp12PButt, 2, 1, 1, 1)
        self.SKE_rp12PButt = QtWidgets.QPushButton(self.SKE_testDEPPButt)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SKE_rp12PButt.sizePolicy().hasHeightForWidth())
        self.SKE_rp12PButt.setSizePolicy(sizePolicy)
        self.SKE_rp12PButt.setMinimumSize(QtCore.QSize(0, 30))
        self.SKE_rp12PButt.setObjectName("SKE_rp12PButt")
        self.gridLayout_12.addWidget(self.SKE_rp12PButt, 2, 3, 1, 1)
        self.label = QtWidgets.QLabel(self.SKE_testDEPPButt)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(40, 30))
        self.label.setObjectName("label")
        self.gridLayout_12.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.SKE_testDEPPButt)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(40, 30))
        self.label_2.setObjectName("label_2")
        self.gridLayout_12.addWidget(self.label_2, 2, 0, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.horizontalLayout_6.setSpacing(10)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.testCyclePeriodNameLabel = QtWidgets.QLabel(self.SKE_testDEPPButt)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.testCyclePeriodNameLabel.sizePolicy().hasHeightForWidth())
        self.testCyclePeriodNameLabel.setSizePolicy(sizePolicy)
        self.testCyclePeriodNameLabel.setMinimumSize(QtCore.QSize(0, 20))
        self.testCyclePeriodNameLabel.setObjectName("testCyclePeriodNameLabel")
        self.horizontalLayout_6.addWidget(self.testCyclePeriodNameLabel)
        self.testCyclePeriodSBox = QtWidgets.QSpinBox(self.SKE_testDEPPButt)
        self.testCyclePeriodSBox.setMinimumSize(QtCore.QSize(70, 30))
        self.testCyclePeriodSBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.testCyclePeriodSBox.setMinimum(1)
        self.testCyclePeriodSBox.setMaximum(3600)
        self.testCyclePeriodSBox.setProperty("value", 10)
        self.testCyclePeriodSBox.setObjectName("testCyclePeriodSBox")
        self.horizontalLayout_6.addWidget(self.testCyclePeriodSBox)
        self.testCycleCBox = QtWidgets.QCheckBox(self.SKE_testDEPPButt)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.testCycleCBox.sizePolicy().hasHeightForWidth())
        self.testCycleCBox.setSizePolicy(sizePolicy)
        self.testCycleCBox.setMinimumSize(QtCore.QSize(0, 30))
        self.testCycleCBox.setIconSize(QtCore.QSize(0, 0))
        self.testCycleCBox.setObjectName("testCycleCBox")
        self.horizontalLayout_6.addWidget(self.testCycleCBox)
        self.gridLayout_12.addLayout(self.horizontalLayout_6, 5, 0, 1, 4)
        self.label_3 = QtWidgets.QLabel(self.SKE_testDEPPButt)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_12.addWidget(self.label_3, 4, 0, 1, 4)
        self.SKE_depM30PButt = QtWidgets.QPushButton(self.SKE_testDEPPButt)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SKE_depM30PButt.sizePolicy().hasHeightForWidth())
        self.SKE_depM30PButt.setSizePolicy(sizePolicy)
        self.SKE_depM30PButt.setMinimumSize(QtCore.QSize(0, 30))
        self.SKE_depM30PButt.setObjectName("SKE_depM30PButt")
        self.gridLayout_12.addWidget(self.SKE_depM30PButt, 0, 2, 1, 1)
        self.verticalLayout_3.addWidget(self.SKE_testDEPPButt)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.horizontalLayout_9.addLayout(self.verticalLayout_3)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.SKE_testGBOX = QtWidgets.QGroupBox(self.SKETab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SKE_testGBOX.sizePolicy().hasHeightForWidth())
        self.SKE_testGBOX.setSizePolicy(sizePolicy)
        self.SKE_testGBOX.setMinimumSize(QtCore.QSize(260, 65))
        self.SKE_testGBOX.setObjectName("SKE_testGBOX")
        self.gridLayout_19 = QtWidgets.QGridLayout(self.SKE_testGBOX)
        self.gridLayout_19.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.gridLayout_19.setObjectName("gridLayout_19")
        self.SKE_SkeTestStartPButt = QtWidgets.QPushButton(self.SKE_testGBOX)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SKE_SkeTestStartPButt.sizePolicy().hasHeightForWidth())
        self.SKE_SkeTestStartPButt.setSizePolicy(sizePolicy)
        self.SKE_SkeTestStartPButt.setMinimumSize(QtCore.QSize(0, 30))
        self.SKE_SkeTestStartPButt.setObjectName("SKE_SkeTestStartPButt")
        self.gridLayout_19.addWidget(self.SKE_SkeTestStartPButt, 0, 0, 1, 1)
        self.SKE_SkeTestStopPButt = QtWidgets.QPushButton(self.SKE_testGBOX)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SKE_SkeTestStopPButt.sizePolicy().hasHeightForWidth())
        self.SKE_SkeTestStopPButt.setSizePolicy(sizePolicy)
        self.SKE_SkeTestStopPButt.setCheckable(False)
        self.SKE_SkeTestStopPButt.setChecked(False)
        self.SKE_SkeTestStopPButt.setObjectName("SKE_SkeTestStopPButt")
        self.gridLayout_19.addWidget(self.SKE_SkeTestStopPButt, 0, 1, 1, 1)
        self.SKE_SkeTestLabel = QtWidgets.QLabel(self.SKE_testGBOX)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SKE_SkeTestLabel.sizePolicy().hasHeightForWidth())
        self.SKE_SkeTestLabel.setSizePolicy(sizePolicy)
        self.SKE_SkeTestLabel.setMinimumSize(QtCore.QSize(150, 25))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.SKE_SkeTestLabel.setFont(font)
        self.SKE_SkeTestLabel.setStyleSheet("")
        self.SKE_SkeTestLabel.setFrameShape(QtWidgets.QFrame.Box)
        self.SKE_SkeTestLabel.setLineWidth(1)
        self.SKE_SkeTestLabel.setMidLineWidth(0)
        self.SKE_SkeTestLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.SKE_SkeTestLabel.setObjectName("SKE_SkeTestLabel")
        self.gridLayout_19.addWidget(self.SKE_SkeTestLabel, 1, 0, 1, 2)
        self.verticalLayout_5.addWidget(self.SKE_testGBOX)
        self.SKE_testResultGBox = QtWidgets.QGroupBox(self.SKETab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SKE_testResultGBox.sizePolicy().hasHeightForWidth())
        self.SKE_testResultGBox.setSizePolicy(sizePolicy)
        self.SKE_testResultGBox.setMinimumSize(QtCore.QSize(260, 0))
        self.SKE_testResultGBox.setMaximumSize(QtCore.QSize(400, 16777215))
        self.SKE_testResultGBox.setObjectName("SKE_testResultGBox")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.SKE_testResultGBox)
        self.horizontalLayout_11.setContentsMargins(1, 1, 1, 1)
        self.horizontalLayout_11.setSpacing(1)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.SKE_testResultTWidget = QtWidgets.QTableWidget(self.SKE_testResultGBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SKE_testResultTWidget.sizePolicy().hasHeightForWidth())
        self.SKE_testResultTWidget.setSizePolicy(sizePolicy)
        self.SKE_testResultTWidget.setMinimumSize(QtCore.QSize(300, 0))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.SKE_testResultTWidget.setFont(font)
        self.SKE_testResultTWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.SKE_testResultTWidget.setRowCount(20)
        self.SKE_testResultTWidget.setObjectName("SKE_testResultTWidget")
        self.SKE_testResultTWidget.setColumnCount(2)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(7)
        item.setFont(font)
        self.SKE_testResultTWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setPointSize(7)
        item.setFont(font)
        self.SKE_testResultTWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.SKE_testResultTWidget.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.SKE_testResultTWidget.setItem(1, 1, item)
        self.SKE_testResultTWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.SKE_testResultTWidget.horizontalHeader().setDefaultSectionSize(170)
        self.SKE_testResultTWidget.horizontalHeader().setMinimumSectionSize(170)
        self.SKE_testResultTWidget.horizontalHeader().setStretchLastSection(True)
        self.SKE_testResultTWidget.verticalHeader().setDefaultSectionSize(30)
        self.SKE_testResultTWidget.verticalHeader().setMinimumSectionSize(30)
        self.horizontalLayout_11.addWidget(self.SKE_testResultTWidget)
        self.verticalLayout_5.addWidget(self.SKE_testResultGBox)
        self.horizontalLayout_9.addLayout(self.verticalLayout_5)
        self.SKE_GrView = QtWidgets.QGraphicsView(self.SKETab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SKE_GrView.sizePolicy().hasHeightForWidth())
        self.SKE_GrView.setSizePolicy(sizePolicy)
        self.SKE_GrView.setObjectName("SKE_GrView")
        self.horizontalLayout_9.addWidget(self.SKE_GrView)
        self.horizontalLayout_9.setStretch(2, 1)
        self.horizontalLayout_10.addLayout(self.horizontalLayout_9)
        self.tabWidget.addTab(self.SKETab, "")
        self.kpaTab = QtWidgets.QWidget()
        self.kpaTab.setObjectName("kpaTab")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.kpaTab)
        self.gridLayout_9.setContentsMargins(5, 5, 5, 5)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout.setSpacing(5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.powerGBox = QtWidgets.QGroupBox(self.kpaTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.powerGBox.sizePolicy().hasHeightForWidth())
        self.powerGBox.setSizePolicy(sizePolicy)
        self.powerGBox.setMinimumSize(QtCore.QSize(250, 70))
        self.powerGBox.setObjectName("powerGBox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.powerGBox)
        self.gridLayout_3.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.gridLayout_3.setContentsMargins(5, 5, 5, 5)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.powOnPButt = QtWidgets.QPushButton(self.powerGBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.powOnPButt.sizePolicy().hasHeightForWidth())
        self.powOnPButt.setSizePolicy(sizePolicy)
        self.powOnPButt.setMinimumSize(QtCore.QSize(0, 30))
        self.powOnPButt.setObjectName("powOnPButt")
        self.gridLayout_3.addWidget(self.powOnPButt, 0, 0, 1, 1)
        self.powOffPButt = QtWidgets.QPushButton(self.powerGBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.powOffPButt.sizePolicy().hasHeightForWidth())
        self.powOffPButt.setSizePolicy(sizePolicy)
        self.powOffPButt.setMinimumSize(QtCore.QSize(0, 30))
        self.powOffPButt.setObjectName("powOffPButt")
        self.gridLayout_3.addWidget(self.powOffPButt, 0, 1, 1, 1)
        self.verticalLayout.addWidget(self.powerGBox)
        self.KUGBox = QtWidgets.QGroupBox(self.kpaTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.KUGBox.sizePolicy().hasHeightForWidth())
        self.KUGBox.setSizePolicy(sizePolicy)
        self.KUGBox.setMinimumSize(QtCore.QSize(250, 110))
        self.KUGBox.setObjectName("KUGBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.KUGBox)
        self.gridLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.gridLayout_2.setContentsMargins(5, 5, 5, 5)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.onBEPButt = QtWidgets.QPushButton(self.KUGBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.onBEPButt.sizePolicy().hasHeightForWidth())
        self.onBEPButt.setSizePolicy(sizePolicy)
        self.onBEPButt.setMinimumSize(QtCore.QSize(30, 30))
        self.onBEPButt.setObjectName("onBEPButt")
        self.gridLayout_2.addWidget(self.onBEPButt, 2, 0, 1, 1)
        self.offBEPButt = QtWidgets.QPushButton(self.KUGBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.offBEPButt.sizePolicy().hasHeightForWidth())
        self.offBEPButt.setSizePolicy(sizePolicy)
        self.offBEPButt.setMinimumSize(QtCore.QSize(30, 30))
        self.offBEPButt.setObjectName("offBEPButt")
        self.gridLayout_2.addWidget(self.offBEPButt, 2, 1, 1, 1)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.durationLabel = QtWidgets.QLabel(self.KUGBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.durationLabel.sizePolicy().hasHeightForWidth())
        self.durationLabel.setSizePolicy(sizePolicy)
        self.durationLabel.setMinimumSize(QtCore.QSize(55, 30))
        self.durationLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.durationLabel.setObjectName("durationLabel")
        self.horizontalLayout_7.addWidget(self.durationLabel)
        self.durationSBox = QtWidgets.QSpinBox(self.KUGBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.durationSBox.sizePolicy().hasHeightForWidth())
        self.durationSBox.setSizePolicy(sizePolicy)
        self.durationSBox.setMinimumSize(QtCore.QSize(25, 30))
        self.durationSBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.durationSBox.setMinimum(15)
        self.durationSBox.setMaximum(500)
        self.durationSBox.setSingleStep(5)
        self.durationSBox.setProperty("value", 20)
        self.durationSBox.setObjectName("durationSBox")
        self.horizontalLayout_7.addWidget(self.durationSBox)
        self.gridLayout_2.addLayout(self.horizontalLayout_7, 3, 0, 1, 2)
        self.verticalLayout.addWidget(self.KUGBox)
        self.testDEPPButt = QtWidgets.QGroupBox(self.kpaTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.testDEPPButt.sizePolicy().hasHeightForWidth())
        self.testDEPPButt.setSizePolicy(sizePolicy)
        self.testDEPPButt.setMinimumSize(QtCore.QSize(250, 80))
        self.testDEPPButt.setObjectName("testDEPPButt")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.testDEPPButt)
        self.gridLayout_4.setContentsMargins(-1, 5, -1, 5)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.depP30PButt = QtWidgets.QPushButton(self.testDEPPButt)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.depP30PButt.sizePolicy().hasHeightForWidth())
        self.depP30PButt.setSizePolicy(sizePolicy)
        self.depP30PButt.setMinimumSize(QtCore.QSize(0, 30))
        self.depP30PButt.setObjectName("depP30PButt")
        self.gridLayout_4.addWidget(self.depP30PButt, 0, 0, 1, 1)
        self.depM30PButt = QtWidgets.QPushButton(self.testDEPPButt)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.depM30PButt.sizePolicy().hasHeightForWidth())
        self.depM30PButt.setSizePolicy(sizePolicy)
        self.depM30PButt.setMinimumSize(QtCore.QSize(0, 30))
        self.depM30PButt.setObjectName("depM30PButt")
        self.gridLayout_4.addWidget(self.depM30PButt, 0, 1, 1, 1)
        self.dep0PButt = QtWidgets.QPushButton(self.testDEPPButt)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dep0PButt.sizePolicy().hasHeightForWidth())
        self.dep0PButt.setSizePolicy(sizePolicy)
        self.dep0PButt.setMinimumSize(QtCore.QSize(0, 30))
        self.dep0PButt.setObjectName("dep0PButt")
        self.gridLayout_4.addWidget(self.dep0PButt, 0, 2, 1, 1)
        self.verticalLayout.addWidget(self.testDEPPButt)
        self.testMPPPButt = QtWidgets.QGroupBox(self.kpaTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.testMPPPButt.sizePolicy().hasHeightForWidth())
        self.testMPPPButt.setSizePolicy(sizePolicy)
        self.testMPPPButt.setMinimumSize(QtCore.QSize(250, 110))
        self.testMPPPButt.setObjectName("testMPPPButt")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.testMPPPButt)
        self.gridLayout_5.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.gridLayout_5.setContentsMargins(5, 5, 5, 5)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.pushButton_3 = QtWidgets.QPushButton(self.testMPPPButt)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_3.sizePolicy().hasHeightForWidth())
        self.pushButton_3.setSizePolicy(sizePolicy)
        self.pushButton_3.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout_5.addWidget(self.pushButton_3, 2, 2, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.testMPPPButt)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_4.sizePolicy().hasHeightForWidth())
        self.pushButton_4.setSizePolicy(sizePolicy)
        self.pushButton_4.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout_5.addWidget(self.pushButton_4, 2, 3, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.testMPPPButt)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_2.sizePolicy().hasHeightForWidth())
        self.pushButton_2.setSizePolicy(sizePolicy)
        self.pushButton_2.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_5.addWidget(self.pushButton_2, 0, 2, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.testMPPPButt)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_5.addWidget(self.pushButton, 0, 3, 1, 1)
        self.verticalLayout.addWidget(self.testMPPPButt)
        self.groupBox = QtWidgets.QGroupBox(self.kpaTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 110))
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_8.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.gridLayout_8.setContentsMargins(5, 5, 5, 5)
        self.gridLayout_8.setSpacing(5)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.adcSinglePButt = QtWidgets.QPushButton(self.groupBox)
        self.adcSinglePButt.setMinimumSize(QtCore.QSize(0, 30))
        self.adcSinglePButt.setObjectName("adcSinglePButt")
        self.gridLayout_8.addWidget(self.adcSinglePButt, 0, 1, 1, 1)
        self.adcCycleCBox = QtWidgets.QCheckBox(self.groupBox)
        self.adcCycleCBox.setMinimumSize(QtCore.QSize(0, 30))
        self.adcCycleCBox.setChecked(True)
        self.adcCycleCBox.setTristate(False)
        self.adcCycleCBox.setObjectName("adcCycleCBox")
        self.gridLayout_8.addWidget(self.adcCycleCBox, 0, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout_4.setContentsMargins(5, 0, 5, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.adcPeriodLabel = QtWidgets.QLabel(self.groupBox)
        self.adcPeriodLabel.setMinimumSize(QtCore.QSize(100, 30))
        self.adcPeriodLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.adcPeriodLabel.setObjectName("adcPeriodLabel")
        self.horizontalLayout_4.addWidget(self.adcPeriodLabel)
        self.adcPeriodSBox = QtWidgets.QDoubleSpinBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.adcPeriodSBox.sizePolicy().hasHeightForWidth())
        self.adcPeriodSBox.setSizePolicy(sizePolicy)
        self.adcPeriodSBox.setMinimumSize(QtCore.QSize(25, 30))
        self.adcPeriodSBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.adcPeriodSBox.setDecimals(1)
        self.adcPeriodSBox.setMinimum(1.0)
        self.adcPeriodSBox.setMaximum(1000.0)
        self.adcPeriodSBox.setProperty("value", 2.0)
        self.adcPeriodSBox.setObjectName("adcPeriodSBox")
        self.horizontalLayout_4.addWidget(self.adcPeriodSBox)
        self.gridLayout_8.addLayout(self.horizontalLayout_4, 1, 0, 1, 2)
        self.verticalLayout.addWidget(self.groupBox)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.line = QtWidgets.QFrame(self.kpaTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line.sizePolicy().hasHeightForWidth())
        self.line.setSizePolicy(sizePolicy)
        self.line.setMinimumSize(QtCore.QSize(360, 10))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.nanswKPALabel = QtWidgets.QLabel(self.kpaTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nanswKPALabel.sizePolicy().hasHeightForWidth())
        self.nanswKPALabel.setSizePolicy(sizePolicy)
        self.nanswKPALabel.setMinimumSize(QtCore.QSize(0, 30))
        self.nanswKPALabel.setAlignment(QtCore.Qt.AlignCenter)
        self.nanswKPALabel.setObjectName("nanswKPALabel")
        self.horizontalLayout_2.addWidget(self.nanswKPALabel)
        self.nanswKPASBox = QtWidgets.QSpinBox(self.kpaTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nanswKPASBox.sizePolicy().hasHeightForWidth())
        self.nanswKPASBox.setSizePolicy(sizePolicy)
        self.nanswKPASBox.setMinimumSize(QtCore.QSize(50, 30))
        self.nanswKPASBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.nanswKPASBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.nanswKPASBox.setObjectName("nanswKPASBox")
        self.horizontalLayout_2.addWidget(self.nanswKPASBox)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.gridLayout_9.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.DataTable = QtWidgets.QTableWidget(self.kpaTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DataTable.sizePolicy().hasHeightForWidth())
        self.DataTable.setSizePolicy(sizePolicy)
        self.DataTable.setMinimumSize(QtCore.QSize(260, 0))
        self.DataTable.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.DataTable.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.DataTable.setRowCount(16)
        self.DataTable.setObjectName("DataTable")
        self.DataTable.setColumnCount(2)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(7)
        item.setFont(font)
        self.DataTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setPointSize(7)
        item.setFont(font)
        self.DataTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.DataTable.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.DataTable.setItem(1, 1, item)
        self.DataTable.horizontalHeader().setCascadingSectionResizes(False)
        self.DataTable.horizontalHeader().setDefaultSectionSize(130)
        self.DataTable.horizontalHeader().setMinimumSectionSize(130)
        self.DataTable.horizontalHeader().setStretchLastSection(True)
        self.DataTable.verticalHeader().setDefaultSectionSize(30)
        self.verticalLayout_4.addWidget(self.DataTable)
        self.ClearLogPButt = QtWidgets.QPushButton(self.kpaTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ClearLogPButt.sizePolicy().hasHeightForWidth())
        self.ClearLogPButt.setSizePolicy(sizePolicy)
        self.ClearLogPButt.setMinimumSize(QtCore.QSize(140, 30))
        self.ClearLogPButt.setObjectName("ClearLogPButt")
        self.verticalLayout_4.addWidget(self.ClearLogPButt)
        self.gridLayout_9.addLayout(self.verticalLayout_4, 0, 1, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.LogTEdit = QtWidgets.QTextEdit(self.kpaTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LogTEdit.sizePolicy().hasHeightForWidth())
        self.LogTEdit.setSizePolicy(sizePolicy)
        self.LogTEdit.setMinimumSize(QtCore.QSize(630, 0))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.LogTEdit.setFont(font)
        self.LogTEdit.setMidLineWidth(0)
        self.LogTEdit.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.LogTEdit.setReadOnly(True)
        self.LogTEdit.setObjectName("LogTEdit")
        self.gridLayout.addWidget(self.LogTEdit, 1, 0, 1, 1)
        self.gridLayout_9.addLayout(self.gridLayout, 0, 2, 1, 1)
        self.gridLayout_9.setColumnStretch(2, 1)
        self.tabWidget.addTab(self.kpaTab, "")
        self.mkoTab = QtWidgets.QWidget()
        self.mkoTab.setObjectName("mkoTab")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.mkoTab)
        self.gridLayout_7.setContentsMargins(5, 5, 5, 5)
        self.gridLayout_7.setSpacing(5)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.scrollArea = QtWidgets.QScrollArea(self.mkoTab)
        self.scrollArea.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setMinimumSize(QtCore.QSize(780, 550))
        self.scrollArea.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.scrollArea.setLineWidth(1)
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 761, 642))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_7.addWidget(self.scrollArea, 0, 0, 1, 1)
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setContentsMargins(5, 5, 5, 5)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.DltUnitNumSBox = QtWidgets.QSpinBox(self.mkoTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DltUnitNumSBox.sizePolicy().hasHeightForWidth())
        self.DltUnitNumSBox.setSizePolicy(sizePolicy)
        self.DltUnitNumSBox.setMinimumSize(QtCore.QSize(0, 25))
        self.DltUnitNumSBox.setObjectName("DltUnitNumSBox")
        self.gridLayout_6.addWidget(self.DltUnitNumSBox, 1, 1, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.mkoTab)
        self.line_2.setMinimumSize(QtCore.QSize(130, 10))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_6.addWidget(self.line_2, 3, 0, 1, 2)
        self.mkoPollingPButt = QtWidgets.QPushButton(self.mkoTab)
        self.mkoPollingPButt.setMinimumSize(QtCore.QSize(0, 30))
        self.mkoPollingPButt.setObjectName("mkoPollingPButt")
        self.gridLayout_6.addWidget(self.mkoPollingPButt, 4, 0, 1, 2)
        self.mkoPollingPBar = QtWidgets.QProgressBar(self.mkoTab)
        self.mkoPollingPBar.setMinimumSize(QtCore.QSize(0, 30))
        self.mkoPollingPBar.setProperty("value", 0)
        self.mkoPollingPBar.setObjectName("mkoPollingPBar")
        self.gridLayout_6.addWidget(self.mkoPollingPBar, 5, 0, 1, 2)
        self.line_5 = QtWidgets.QFrame(self.mkoTab)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.gridLayout_6.addWidget(self.line_5, 6, 0, 1, 2)
        self.SaveCfgPButt = QtWidgets.QPushButton(self.mkoTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SaveCfgPButt.sizePolicy().hasHeightForWidth())
        self.SaveCfgPButt.setSizePolicy(sizePolicy)
        self.SaveCfgPButt.setMinimumSize(QtCore.QSize(130, 30))
        self.SaveCfgPButt.setObjectName("SaveCfgPButt")
        self.gridLayout_6.addWidget(self.SaveCfgPButt, 8, 0, 1, 2)
        self.DltAllUnitsPButt = QtWidgets.QPushButton(self.mkoTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DltAllUnitsPButt.sizePolicy().hasHeightForWidth())
        self.DltAllUnitsPButt.setSizePolicy(sizePolicy)
        self.DltAllUnitsPButt.setMinimumSize(QtCore.QSize(130, 30))
        self.DltAllUnitsPButt.setObjectName("DltAllUnitsPButt")
        self.gridLayout_6.addWidget(self.DltAllUnitsPButt, 2, 0, 1, 2)
        self.DltUnitPButt = QtWidgets.QPushButton(self.mkoTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DltUnitPButt.sizePolicy().hasHeightForWidth())
        self.DltUnitPButt.setSizePolicy(sizePolicy)
        self.DltUnitPButt.setMinimumSize(QtCore.QSize(60, 30))
        self.DltUnitPButt.setObjectName("DltUnitPButt")
        self.gridLayout_6.addWidget(self.DltUnitPButt, 1, 0, 1, 1)
        self.line_6 = QtWidgets.QFrame(self.mkoTab)
        self.line_6.setMinimumSize(QtCore.QSize(0, 10))
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.gridLayout_6.addWidget(self.line_6, 9, 0, 1, 2)
        self.AddUnitPButt = QtWidgets.QPushButton(self.mkoTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.AddUnitPButt.sizePolicy().hasHeightForWidth())
        self.AddUnitPButt.setSizePolicy(sizePolicy)
        self.AddUnitPButt.setMinimumSize(QtCore.QSize(225, 30))
        self.AddUnitPButt.setObjectName("AddUnitPButt")
        self.gridLayout_6.addWidget(self.AddUnitPButt, 0, 0, 1, 2)
        self.LoadCfgPButt = QtWidgets.QPushButton(self.mkoTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LoadCfgPButt.sizePolicy().hasHeightForWidth())
        self.LoadCfgPButt.setSizePolicy(sizePolicy)
        self.LoadCfgPButt.setMinimumSize(QtCore.QSize(130, 30))
        self.LoadCfgPButt.setObjectName("LoadCfgPButt")
        self.gridLayout_6.addWidget(self.LoadCfgPButt, 7, 0, 1, 2)
        self.cycleStartPButt = QtWidgets.QPushButton(self.mkoTab)
        self.cycleStartPButt.setMinimumSize(QtCore.QSize(0, 30))
        self.cycleStartPButt.setObjectName("cycleStartPButt")
        self.gridLayout_6.addWidget(self.cycleStartPButt, 11, 0, 1, 2)
        spacerItem3 = QtWidgets.QSpacerItem(231, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem3, 18, 0, 1, 2)
        self.cycleNumLabel = QtWidgets.QLabel(self.mkoTab)
        self.cycleNumLabel.setMinimumSize(QtCore.QSize(0, 30))
        self.cycleNumLabel.setObjectName("cycleNumLabel")
        self.gridLayout_6.addWidget(self.cycleNumLabel, 14, 0, 1, 1)
        self.cycleIntervalLabel = QtWidgets.QLabel(self.mkoTab)
        self.cycleIntervalLabel.setMinimumSize(QtCore.QSize(0, 30))
        self.cycleIntervalLabel.setObjectName("cycleIntervalLabel")
        self.gridLayout_6.addWidget(self.cycleIntervalLabel, 13, 0, 1, 1)
        self.cycleElapsedTimeTEdit = QtWidgets.QTimeEdit(self.mkoTab)
        self.cycleElapsedTimeTEdit.setMinimumSize(QtCore.QSize(0, 30))
        self.cycleElapsedTimeTEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.cycleElapsedTimeTEdit.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.cycleElapsedTimeTEdit.setObjectName("cycleElapsedTimeTEdit")
        self.gridLayout_6.addWidget(self.cycleElapsedTimeTEdit, 15, 1, 1, 1)
        self.cycleIntervalSBox = QtWidgets.QDoubleSpinBox(self.mkoTab)
        self.cycleIntervalSBox.setMinimumSize(QtCore.QSize(0, 30))
        self.cycleIntervalSBox.setDecimals(1)
        self.cycleIntervalSBox.setMinimum(0.5)
        self.cycleIntervalSBox.setMaximum(100000.0)
        self.cycleIntervalSBox.setSingleStep(0.1)
        self.cycleIntervalSBox.setProperty("value", 0.5)
        self.cycleIntervalSBox.setObjectName("cycleIntervalSBox")
        self.gridLayout_6.addWidget(self.cycleIntervalSBox, 13, 1, 1, 1)
        self.cyclePBar = QtWidgets.QProgressBar(self.mkoTab)
        self.cyclePBar.setMinimumSize(QtCore.QSize(0, 30))
        self.cyclePBar.setProperty("value", 0)
        self.cyclePBar.setObjectName("cyclePBar")
        self.gridLayout_6.addWidget(self.cyclePBar, 16, 0, 1, 2)
        self.cycleFullTimeLabel = QtWidgets.QLabel(self.mkoTab)
        self.cycleFullTimeLabel.setMinimumSize(QtCore.QSize(0, 30))
        self.cycleFullTimeLabel.setObjectName("cycleFullTimeLabel")
        self.gridLayout_6.addWidget(self.cycleFullTimeLabel, 15, 0, 1, 1)
        self.cycleNumSBox = QtWidgets.QSpinBox(self.mkoTab)
        self.cycleNumSBox.setMinimumSize(QtCore.QSize(0, 30))
        self.cycleNumSBox.setMinimum(1)
        self.cycleNumSBox.setMaximum(100000)
        self.cycleNumSBox.setProperty("value", 100)
        self.cycleNumSBox.setObjectName("cycleNumSBox")
        self.gridLayout_6.addWidget(self.cycleNumSBox, 14, 1, 1, 1)
        self.cycleStopPButt = QtWidgets.QPushButton(self.mkoTab)
        self.cycleStopPButt.setMinimumSize(QtCore.QSize(0, 30))
        self.cycleStopPButt.setObjectName("cycleStopPButt")
        self.gridLayout_6.addWidget(self.cycleStopPButt, 17, 0, 1, 2)
        self.gridLayout_7.addLayout(self.gridLayout_6, 0, 1, 1, 1)
        self.mkoDataTable = QtWidgets.QTableWidget(self.mkoTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mkoDataTable.sizePolicy().hasHeightForWidth())
        self.mkoDataTable.setSizePolicy(sizePolicy)
        self.mkoDataTable.setMinimumSize(QtCore.QSize(260, 0))
        self.mkoDataTable.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.mkoDataTable.setRowCount(20)
        self.mkoDataTable.setObjectName("mkoDataTable")
        self.mkoDataTable.setColumnCount(2)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(7)
        item.setFont(font)
        self.mkoDataTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setPointSize(7)
        item.setFont(font)
        self.mkoDataTable.setHorizontalHeaderItem(1, item)
        self.mkoDataTable.horizontalHeader().setCascadingSectionResizes(False)
        self.mkoDataTable.horizontalHeader().setDefaultSectionSize(130)
        self.mkoDataTable.horizontalHeader().setMinimumSectionSize(50)
        self.mkoDataTable.horizontalHeader().setStretchLastSection(True)
        self.mkoDataTable.verticalHeader().setDefaultSectionSize(30)
        self.gridLayout_7.addWidget(self.mkoDataTable, 0, 2, 1, 1)
        self.gridLayout_7.setColumnStretch(2, 1)
        self.tabWidget.addTab(self.mkoTab, "")
        self.gridLayout_14.addWidget(self.tabWidget, 0, 0, 1, 1)
        main_win.setCentralWidget(self.centralwidget)

        self.retranslateUi(main_win)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(main_win)

    def retranslateUi(self, main_win):
        _translate = QtCore.QCoreApplication.translate
        main_win.setWindowTitle(_translate("main_win", "КПА СКЭ-ЛР КЛИЕНТ"))
        self.logsUpdatePButt.setText(_translate("main_win", "Создать новый лог-файл"))
        self.connectPButt.setText(_translate("main_win", "Подключить"))
        self.disconnectPButt.setText(_translate("main_win", "Отключить"))
        self.SKE_powerGBox.setTitle(_translate("main_win", "Питание"))
        self.SKE_powOnPButt.setText(_translate("main_win", "Включить"))
        self.SKE_powOffPButt.setText(_translate("main_win", "Выключить"))
        self.SKE_KUGBox.setTitle(_translate("main_win", "Команды управления"))
        self.SKE_durationLabel.setText(_translate("main_win", "Длительность, мс"))
        self.SKE_onBEPButt.setText(_translate("main_win", "ВКЛ БЭ"))
        self.SKE_offBEPButt.setText(_translate("main_win", "ВЫКЛ БЭ"))
        self.SKE_powDataGBox.setTitle(_translate("main_win", "Параметры питания"))
        self.SKE_powULabel.setText(_translate("main_win", "Напряжение, В"))
        self.SKE_powLabel.setText(_translate("main_win", "Мощность, Вт"))
        self.SKE_powILabel.setText(_translate("main_win", "Ток, мА"))
        self.groupBox_7.setTitle(_translate("main_win", "СТМ-параметры"))
        self.SKE_stmNormCM_Label.setText(_translate("main_win", "НормЦМ, В"))
        self.SKE_stmAMKO_Label.setText(_translate("main_win", "АМКО, В"))
        self.SKE_stmKPBE_Label.setText(_translate("main_win", "КПБЭ, В"))
        self.SKE_measIntervalGBox.setTitle(_translate("main_win", "Режимы измерения"))
        self.SKE_mInterval60sRButt.setText(_translate("main_win", "60 секунд"))
        self.SKE_mInterval240sRButt.setText(_translate("main_win", "240 секунд"))
        self.SKE_mInterval120sRButt.setText(_translate("main_win", "120 секунд"))
        self.SKE_mInterval1sPButton.setText(_translate("main_win", "Ускоренный режим"))
        self.SKE_dbgMIntPbutton.setText(_translate("main_win", "Отладочный режим"))
        self.SKE_testDEPPButt.setTitle(_translate("main_win", "Тестовые сигналы"))
        self.SKE_dnp_drp_PButt.setText(_translate("main_win", "ДНП, ДРП"))
        self.SKE_dep0PButt.setText(_translate("main_win", "0 В"))
        self.SKE_depP30PButt.setText(_translate("main_win", "+ U"))
        self.SKE_mpp12PButt.setText(_translate("main_win", "МПП 1-2"))
        self.SKE_rp12PButt.setText(_translate("main_win", "РП 1-2"))
        self.label.setText(_translate("main_win", "ДЭП"))
        self.label_2.setText(_translate("main_win", "МПП"))
        self.testCyclePeriodNameLabel.setText(_translate("main_win", "Интервал цикла, с"))
        self.testCycleCBox.setText(_translate("main_win", "Запуск/Стоп"))
        self.label_3.setText(_translate("main_win", "Циклическое задание воздействий"))
        self.SKE_depM30PButt.setText(_translate("main_win", "- U"))
        self.SKE_testGBOX.setTitle(_translate("main_win", "Тестирование"))
        self.SKE_SkeTestStartPButt.setText(_translate("main_win", "Запуск"))
        self.SKE_SkeTestStopPButt.setText(_translate("main_win", "Остановить"))
        self.SKE_SkeTestLabel.setText(_translate("main_win", "..."))
        self.SKE_testResultGBox.setTitle(_translate("main_win", "Результаты тестирования"))
        item = self.SKE_testResultTWidget.horizontalHeaderItem(0)
        item.setText(_translate("main_win", "Имя"))
        item = self.SKE_testResultTWidget.horizontalHeaderItem(1)
        item.setText(_translate("main_win", "Значение"))
        __sortingEnabled = self.SKE_testResultTWidget.isSortingEnabled()
        self.SKE_testResultTWidget.setSortingEnabled(False)
        self.SKE_testResultTWidget.setSortingEnabled(__sortingEnabled)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.SKETab), _translate("main_win", "СКЭ"))
        self.powerGBox.setTitle(_translate("main_win", "Питание"))
        self.powOnPButt.setText(_translate("main_win", "Включить"))
        self.powOffPButt.setText(_translate("main_win", "Выключить"))
        self.KUGBox.setTitle(_translate("main_win", "Команды управления"))
        self.onBEPButt.setText(_translate("main_win", "ВКЛ БЭ"))
        self.offBEPButt.setText(_translate("main_win", "ВЫКЛ БЭ"))
        self.durationLabel.setText(_translate("main_win", "Tимп, мс"))
        self.testDEPPButt.setTitle(_translate("main_win", "Тестовый сигнал для ДЭП-ов"))
        self.depP30PButt.setText(_translate("main_win", "+ U"))
        self.depM30PButt.setText(_translate("main_win", "- U"))
        self.dep0PButt.setText(_translate("main_win", "0 В"))
        self.testMPPPButt.setTitle(_translate("main_win", "Тестовый сигнал МПП"))
        self.pushButton_3.setText(_translate("main_win", "Канал 2"))
        self.pushButton_4.setText(_translate("main_win", "Канал 4"))
        self.pushButton_2.setText(_translate("main_win", "Канал 1"))
        self.pushButton.setText(_translate("main_win", "Канал 3"))
        self.groupBox.setTitle(_translate("main_win", "АЦП"))
        self.adcSinglePButt.setText(_translate("main_win", "Разовый запрос"))
        self.adcCycleCBox.setText(_translate("main_win", "Циклический опрос"))
        self.adcPeriodLabel.setText(_translate("main_win", "Интервал циклического опроса, с:"))
        self.nanswKPALabel.setText(_translate("main_win", "Количество неответов КПА, шт"))
        item = self.DataTable.horizontalHeaderItem(0)
        item.setText(_translate("main_win", "Имя"))
        item = self.DataTable.horizontalHeaderItem(1)
        item.setText(_translate("main_win", "Значение"))
        __sortingEnabled = self.DataTable.isSortingEnabled()
        self.DataTable.setSortingEnabled(False)
        self.DataTable.setSortingEnabled(__sortingEnabled)
        self.ClearLogPButt.setText(_translate("main_win", "Очистить лог"))
        self.LogTEdit.setHtml(_translate("main_win", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Courier New\'; font-size:7pt; font-weight:600; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'PT Serif\'; font-size:8.25pt; font-weight:400;\"><br /></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.kpaTab), _translate("main_win", "КПА"))
        self.mkoPollingPButt.setText(_translate("main_win", "Разовый опрос всех команд"))
        self.SaveCfgPButt.setText(_translate("main_win", "Сохранить"))
        self.DltAllUnitsPButt.setText(_translate("main_win", "Удалить все"))
        self.DltUnitPButt.setText(_translate("main_win", "Удалить"))
        self.AddUnitPButt.setText(_translate("main_win", "Добавить"))
        self.LoadCfgPButt.setText(_translate("main_win", "Загрузить"))
        self.cycleStartPButt.setText(_translate("main_win", "Запуск циклического опроса"))
        self.cycleNumLabel.setText(_translate("main_win", "Количество, шт"))
        self.cycleIntervalLabel.setText(_translate("main_win", "Интервал, с"))
        self.cycleElapsedTimeTEdit.setDisplayFormat(_translate("main_win", "H:mm:ss"))
        self.cycleFullTimeLabel.setText(_translate("main_win", "Осталось , c"))
        self.cycleStopPButt.setText(_translate("main_win", "Оставновить цикл"))
        item = self.mkoDataTable.horizontalHeaderItem(0)
        item.setText(_translate("main_win", "Имя"))
        item = self.mkoDataTable.horizontalHeaderItem(1)
        item.setText(_translate("main_win", "Значение"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.mkoTab), _translate("main_win", "МПИ"))

